#!/usr/bin/env bash
#var1=$(swapon -s | tail -1 |  awk '{print$1,$3}' | cut -d '/' -f 2)
availMem=$(swapon -s | tail -1 |  awk '{print$3}' | cut -d '/' -f 2)
gb=$(awk "BEGIN {print $availMem/1024/1020}")

add_swap() {
   su="$(id -u)"
   swap_size="$var"
   m=$(($var * 2))



   dis=$(df -H | grep -vE '^Filesystem|tmpfs|cdrom|loop|udev' | head -n 1)
   disk=$(df -H | grep -vE '^Filesystem|tmpfs|cdrom|loop|udev' | awk '{ print $4}' | rev | cut -c2- | rev | head -n 1)
  # d=$((disk * 1024))
    d=$(echo "$disk * 1024" | bc)
    D=${d%.*}

 if [ "$var" == "" ]
 then
   echo "Please Define Argument (eg. - if you want add swap 8GB than define argument:- 8 "
   exit 2
 elif [ "$su" != 0 ]
 then
   echo "Please Execute Script as sudo user"
   exit 3
 elif [ "$D" -le "$m" ]
 then
   echo "Please Check Disk Space,Now is: $dis"
   echo "Memory Space is : $var "
   exit 4
 else
  #Creating a Swap File
  sudo fallocate -l "$swap_size"M /swapfile
  #Enabling the Swap File
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile
  sudo swapon /swapfile
  #Making the Swap File Permanent
  sudo cp /etc/fstab /etc/fstab.bak
  #echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
  echo '/swapfile   swap    swap    sw  0   0' | sudo tee -a /etc/fstab
  #Tuning your Swap Settings
   isInFile=$(cat /etc/sysctl.conf | grep -c "vm.swappiness=10")

   if [ $isInFile -eq 0 ]; then
      echo "vm.swappiness=10" >> /etc/sysctl.conf
      echo "vm.vfs_cache_pressure=80" >> /etc/sysctl.conf
   else
      sed -i 's/vm.swappiness=10/vm.swappiness=10/g' /etc/sysctl.conf
      sed -i 's/vm.vfs_cache_pressure=80/vm.vfs_cache_pressure=80/g' /etc/sysctl.conf

   fi
  sudo sysctl -p
 fi
}

swapsize(){
    arg=""
    mem=$(free -m | grep Mem |awk '{print $2}')

    if [ "$mem" -lt 2048 ]
    then
      arg=$(("$mem" * 2))

    elif [ "$mem" -gt 2048 ] && [ "$mem" -le 8192 ]
    then
       arg="$mem"
    elif [ "$mem" -gt 8192 ] && [ "$mem" -le 65536 ]
    then
       arg="$(($mem / 2))"
    else
       echo "Memory Size out of defined range"
    fi
    echo "$arg"
}
var=$( swapsize )


check(){
  echo -n " Do you want to add swap memory? (y/n): "; read proceed
   if [ "$proceed" == "y" ]; then
      echo ""
      add_swap
      echo "Setup swap complete! Check output to confirm everything is good."
   else
     echo "You choose to exit."
     exit 1
   fi
}


function Main() {
    #check if swap is on
    isSwapOn=$(swapon -s | tail -1)

    if [[ "$isSwapOn" == "" ]]; then
        echo "No swap has been configured"
        echo ""
        check
    else
        echo "Swap Already Available. If required, firstly remove swap and then execute script again."
        echo "current Swap is: $gb G"
        exit 1
      #  removeSwap
      #  createSwap
    fi
}

Main


# output results to terminal
cat /proc/swaps
cat /proc/meminfo | grep Swap
